seed: 666
data_path: ./images
train_batch_size: 4
eval_batch_size: 2
num_workers: 1
max_epochs: 100
train_epoch_length: 10
eval_epoch_length: 10
lr: 0.0001
use_amp: false
debug: false
model: resnet50
filename_prefix: training
n_saved: 2
save_every_iters: 100
patience: 3
output_dir: ./logs
log_every_iters: 2
num_classes: 3
